### ISSUE TITLE
Aether Performance Improvement

### ISSUE THREAD

**Issue by rainysux** [Gilded-Games/The-Aether#1844] opened 2023-11-11 18:42 UTC
### What Type of Bug Is This?

Performance

### Forge Version

1.47.1.3

### The Aether Version

The Aether - 1.20.1-1.0.0-beta.1.4-neoforge

### Steps to Reproduce

Run in a server
Run Spark 
See aether usage outside of the aether

### What You Expect To Happen

Hoping for this ti be improved upon

### What Actually Happened

I noticed that the aether is ticking for biomes and entities almost every tick while youre not in it

### Additional Details

devs in the modernfix discord recommend this to improve performance “they can rewrite the logic to be entity-specific
to be in entity ticking” “they should do that too, but reordering the if statements would already be enough to fix the problem and they shouldn't bother doing any of this logic when not in the aether”

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by Builderdog841** [comment] 2023-11-11 18:44
I personally have any performance issues with the aether. Are sure it's not an add-on causing that?

**Comment by rainysux** [comment] 2023-11-11 18:46
> I personally have any performance issues with the aether. Are sure it's not an add-on causing that?

Its not a issue per say but its something that can be improved upon.

**Comment by rainysux** [comment] 2023-11-11 18:47
It's unnecessary for it tick for the aether to tick for biomes and entities even while you're not in it

**Comment by bconlon1** [comment] 2023-11-29 01:00
Sounds to be a duplicate of #1841.

**Closed as not planned by bconlon1** 2023-11-29 01:00 UTC

**Comment by bconlon1** [comment] 2023-12-01 04:06
A commit has been pushed that may fix this issue, it will need testing: https://output.circle-artifacts.com/output/job/0dcf30b1-84de-47b2-b572-fc07fc27bbe2/artifacts/0/~/project/build/libs/aether-1.20.1-1.0.0-beta.1.4-neoforge.jar
