### ISSUE TITLE
Bug: Crash On world Load with 

### ISSUE THREAD

**Issue by drhaber** [Gilded-Games/The-Aether#2322] opened 2024-10-15 18:03 UTC
### What Feature Types Apply to This Bug?

Other (Please Describe)

### Other Type

World Load

### What Type of Bug Is This?

Crash

### Forge Version

47.3.7

### The Aether Version

1.5.0

### Is This Bug a Conflict With Another Mod?

Not Sure

### Client Log

https://mclo.gs/hRZJF6A

### Crash Report (if applicable)

https://mclo.gs/hRZJF6A

### Steps to Reproduce

Load a world after upating Aether

### What You Expect To Happen

a world to load 

### What Actually Happened

crashed on world load

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by Builderdog841** [comment] 2024-10-15 18:08
the crash is caused by Aether Redux and Ancient Aether due both not being compatible with the latest Aether Update, either uninstall both mods or downgrade your aether version

**Comment by raffle2** [comment] 2024-10-15 21:02
Same issue here. I will keep it downgraded for now!

**Comment by bconlon1** [comment] 2024-10-16 19:01
Duplicate of #2308

**Closed as not planned by bconlon1** 2024-10-16 19:01 UTC
