### ISSUE TITLE
Bug: Incubator gui does not exist

### ISSUE THREAD

**Issue by kodadacod** [Gilded-Games/The-Aether#416] opened 2022-01-17 19:41 UTC
### What Feature Types Apply to This Bug?

Block

### What Type of Bug Is This?

Annoyance

### Forge Version

39.0.40

### The Aether 1 Version

1.0.0

### Steps to Reproduce

1. Obtain an Incubator
2. Place it down
3. Interact with it

### What You Expect To Happen

A gui for incubating a moa egg would show up

### What Actually Happened

No gui shows up

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment] 2022-01-17 19:45
Duplicate of #144

**Closed as completed by bconlon1** 2022-01-17 19:45 UTC
