### ISSUE TITLE
Bug: Custom dimensions using the Aether's dimension effect crash the game

### ISSUE THREAD

**Issue by muzikbike** [Gilded-Games/The-Aether#473] opened 2022-03-04 01:09 UTC
### What Feature Types Apply to This Bug?

World-Gen

### What Type of Bug Is This?

Crash

### Forge Version

39.0.88

### The Aether 1 Version

1.18.1-v1.0.0

### Steps to Reproduce

1. Create a new world with the following data pack: [aecrash.zip](https://github.com/Gilded-Games/The-Aether/files/8182222/aecrash.zip)
2. Enter spectator mode
3. /execute in aecrash:i_work_fine run tp ~ ~ ~
4. Note that the game doesn't crash
5. /execute in aecrash:death_test run tp ~ ~ ~
6. Watch as the game hangs for about three minutes, cuts to a screen made of blue dirt and then closes itself

### What You Expect To Happen

An empty dimension with the Aether's dimension effects would be accessed.

### What Actually Happened

We get a crash.

### Additional Details

Crash report not attached since it's probably not necessary - the issue was discussed as being plausible enough in Discord

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment] 2022-03-25 17:37
This might be fixed by the recent addition of the `#eternal_day` dimension type tag; needs further testing.

**Comment by bconlon1** [comment] 2022-03-25 22:51
Your datapack does not work from trying to follow the given steps, please link a new one or update the steps.

**Comment by bconlon1** [comment] 2022-03-25 23:40
Nevermind, created a working datapack and confirmed that the recent addition of `#eternal_day` fixes this as long as a dimension's dimension type is put into the tag.

**Closed as completed** 2022-03-27 23:45 UTC
Labels: status/confirmed, status/pending-review

**Comment by bconlon1** [comment] 2022-04-02 20:55
This may not have actually been fully fixed by the PR that closed this issue due to the issue also regarding DimensionTypeMixin, however it will likely have to remain closed due to other issues relating to #531, i.e. other dimensions should not be trying to hook into Aether-specific behavior yet.
