### ISSUE TITLE
Bug: Cockatrices reuse the moa sound event

### ISSUE THREAD

**Issue by muzikbike** [Gilded-Games/The-Aether#65] opened 2021-03-05 22:25 UTC
They should probably get their own so it's less confusing when subtitle strings are added:
![2021-03-05_22 24 08](https://user-images.githubusercontent.com/52297970/110180463-b748ca00-7e01-11eb-95ec-dc57272e32de.png)

**Comment by bconlon1** [comment] 2021-05-24 17:19
This will be fixed whenever I reorganize the sounds.json file.

**Comment by bconlon1** [comment] 2022-01-20 06:08
Duplicate of #261.

**Closed as completed by bconlon1** 2022-01-20 06:08 UTC
Labels: status/confirmed, type/design, feat/entity
