### ISSUE TITLE
Enhancement: Unique ore patterns

### ISSUE THREAD

**Issue by muzikbike** [Gilded-Games/The-Aether#54] opened 2021-03-05 03:59 UTC
Might be resolved like #39 was. But currently the ore textures are all the same, so it might be advisable to change the patterns to all be different for non-programmer art (maybe get this in early for 1.16).

**Comment by ghost** [comment] 2021-03-26 14:33
Yeah, this would count as a duplicate of #39 but I'm currently working a texture pack which is meant to replicate Jappa's art style for the Aether. I can't promise it'll be out anytime soon but you can hopefully expect it sometime in the future

**Comment by bconlon1** [comment] 2022-05-17 16:00
Has been fulfilled in the retextures.

**Closed as completed by bconlon1** 2022-05-17 16:00 UTC
Labels: priority/high, type/request, feat/art
