### ISSUE TITLE
Bug: Transparent areas

### ISSUE THREAD

**Issue by norbertmyrta98** [Gilded-Games/The-Aether#1734] opened 2023-09-19 10:26 UTC
### What Feature Types Apply to This Bug?

World-Gen

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

43.2.6

### The Aether Version

1.19.2-1.0.0-beta1.1 forge and beta1.0 forge

### Steps to Reproduce

Aether dimension and overworld for sure. in game, without mod does not appear. appears in random pleaces. with and without other generation mods occur

### What You Expect To Happen

Textures shouldnt be transparent in some chunks

### What Actually Happened

![2023-09-18_19 45 53](https://github.com/The-Aether-Team/The-Aether/assets/118357663/9091da16-c0be-44bf-9c47-bd8d11e3af02)
![2023-09-19_12 11 34](https://github.com/The-Aether-Team/The-Aether/assets/118357663/89d7b6d3-eb37-4d8c-9f53-8e00204e5dc5)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by OzPayn** [comment] 2023-09-19 13:16
I believe this is caused by Rubidium but should be fixed on the latest release, so I'd advise you to update your Rubidium mod

**Closed as not planned** 2023-09-19 18:40 UTC
