### ISSUE TITLE
broken discs

### ISSUE THREAD

**Issue by SLIMEMASTER000** [Gilded-Games/The-Aether#1607] opened 2023-08-06 23:57 UTC
### What Feature Types Apply to This Bug?

Audio

### What Type of Bug Is This?

Design

### Forge Version

45.1.16

### The Aether Version

aether-1.19.4-1.0.0-beta.5.1-forge.jar

### Is This Bug a Conflict With Another Mod?

nope

### Steps to Reproduce

get a ren ren music disc and play it 

### What You Expect To Happen

ether chinchila or high plays and a can jam

### What Actually Happened

S I L A N C E

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment] 2023-08-06 23:57
Duplicate of #1592

**Closed as not planned by bconlon1** 2023-08-06 23:57 UTC
