### ISSUE TITLE
Too many cockatrices

### ISSUE THREAD

**Issue by Aethyus** [Gilded-Games/The-Aether#596] opened 2022-05-14 14:35 UTC
### Forge Version

39.0.0

### The Aether 1 Version

1.1.0

### Is This Bug a Conflict With Another Mod?

No

### Steps to Reproduce

1. Go into the Aether.
2. Look for a cave/a place out of daylight.
3. Instead of a few cockatrices, (2 to 3), there are sometimes up to 9.

### What You Expect To Happen

Normally in the Aether 1, at least the old versions of the game, there is not such a large amount of cockatrices.

### What Actually Happened

Unlike older versions, when you go to dark places, there are sometimes a dozen cockatrices.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment] 2022-05-14 14:36
Duplicate of #262

**Closed as completed by bconlon1** 2022-05-14 14:36 UTC

**Comment by Aethyus** [comment] 2022-05-14 14:38
Ah I had not seen, I thought it did not concern cockatrices. sorry !
