### ISSUE TITLE
Curios accessories don't function with the new right click to swap equips on hotbar feature from 1.19.4

### ISSUE THREAD

**Issue by sunsetbear** [Gilded-Games/The-Aether#1106] opened 2023-03-28 03:23 UTC
### What Feature Types Apply to This Bug?

Item

### What Type of Bug Is This?

Annoyance

### Forge Version

45.0.22

### The Aether Version

1.19.4-0.5.1

### Steps to Reproduce

1. Hold an equippable item whose slot is already full.
2. Right-click.

### What You Expect To Happen

The item would swap itself with the item equipped in its respective slot, like the new 1.19.4 feature.

### What Actually Happened

Nothing.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by Burning-Cactus** [comment] 2023-03-28 03:38
Duplicate of #1068

**Closed as completed by Burning-Cactus** 2023-03-28 03:38 UTC
