### ISSUE TITLE
Bug: Mining Curse of the Picking Favorites

### ISSUE THREAD

**Issue by MinerB4** [Gilded-Games/The-Aether#1848] opened 2023-11-25 07:51 UTC
### What Feature Types Apply to This Bug?

Block, Item

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

1.20.1-47.2.6

### The Aether Version

1.20.1-1.0.0-beta.1.4

### Client Log

N/A

### Steps to Reproduce

Mine a block from "The Aether" mod with any pickaxe in wood-diamond tier (from Minecraft),
Use a netherite-tier pickaxe (from Minecraft) to mine the same block.
Take notice of the time difference... or more so the lack thereof.
Use any pickaxe from "The Aether" to mine the same block.
Take note of the faster mine speeds.

### What You Expect To Happen

![image](https://github.com/The-Aether-Team/The-Aether/assets/70791904/04c1803d-8a7e-436b-991f-e01f558e80e4)
I feel like the pickaxe I got from fungus hell should be better than a wood pickaxe I literally made in the sky.

### What Actually Happened

![image](https://github.com/The-Aether-Team/The-Aether/assets/70791904/1d2c7d12-3191-4548-81e9-912bf9269531)
Wood pickaxe I made in the sky beat the pickaxe I literally forged from within the depths of fungus hell.

### Additional Details

This error was initially discovered in a modpack my friend created, however is replicable in it's own private instance.
Wooden, Stone, Iron, Gold, Diamond, and Netherite tools all share the same speed and it is unclear if this is the intended effect or an oversight.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by OzPayn** [comment] 2023-11-25 09:17
This is a feature of the mod, not a bug. It can be disabled through the mod's configs (specifically the server/world config)

Intentional behaviour, closing the issue

**Closed as completed by OzPayn** 2023-11-25 09:17 UTC
