### ISSUE TITLE
Ruined Aether Portals

### ISSUE THREAD

**Issue by Meowthexe1984** [Gilded-Games/The-Aether#1107] opened 2023-03-30 22:24 UTC
### What Feature Types Apply to This Request?

Other (Please Describe)

### Other Type

Structure

### Is This an Enhancement to a Preexisting Feature?

- [ ] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

The ruined aether portal is a naturally generated damaged aether portal, which spawns in both the Aether and the Overworld. It contains some decoration and a loot chest around it. Ruined aether portals are the opposite of Ruined nether portals.

**Structure**
Ruined aether portals were designed to look like the opposite of Ruined nether portals. generate incomplete portal frames composed of glowstone instead of obsidian. Some frames generate flat on the ground, as if they toppled over. Others are free-standing separately, as if still being assembled/attached.

All ruined portals generate with a chest on Java Edition the skyroot chest may be replaced if terrain overrides it. Each skyroot chest contains various diamond items and items used to build portals such as glowstone and water bucket instead of obsidian and flint and steel.

Any ruined portal generated in the Overworld is surrounded with structures made of stone, stone bricks, and iron bars; in the Aether it is surrounded by therastone variants (instead of blackstone) and chains.

Currently there are 13 variants: 10 normal size portals and 3 giant portals in varying states of decay.

 **Original Block**
- Block of Diamond
- Water - Instead of Lava
- Aether Grass
- Glowstone
- Stone
- Stone Bricks
- Chiseled Stone Bricks

 **Relpacing Blocks**
- Air
- Aether Grass
- Enchanted Aether Grass
- Cracked Stone Bricks
- Mossy Stone Brick Stairs
- Mossy Stone Brick Slab
- Stone Slab
- Stone Brick Slab
- Mossy Stone Brick Wall

### Why Should It Be in the Mod?

Ruined aether portals are the only generated structures that generate in more than one dimension; they generate in all biomes in both the Aether and the Overworld. They can spawn underground, underwater, or exposed to the air. If they generate underground, they have air pockets around them. Natural terrain around ruined aether portals generates as aether grass. They also generate a mass of aether dirt underneath them. Giant ruined portals have 3 distinct designs, and normal ruined aether portals have 10 designs. When a ruined aether portal generates, it has a 5% chance to be a giant ruined aether portal, for about a 1.67% chance per giant portal design. This gives normal ruined portals a 95% chance, for a 9.5% chance per normal ruined portal design.

### Does This Feature Improve Compatibility With Another Mod?

The Aether

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment] 2023-03-30 22:27
Duplicate of #1045. We've already got some ideas and concepts for what we'd do with ruined portals if we are to implement them. Although we will likely be open to some feedback if we do, but that may not happen until beta.

**Closed as not planned by bconlon1** 2023-03-30 22:27 UTC
Labels: type/request
