### ISSUE TITLE
Bug: Aerogel wall item model needs fixed to remove internal planes

### ISSUE THREAD

**Issue by muzikbike** [Gilded-Games/The-Aether#477] opened 2022-03-05 02:10 UTC
### What Feature Types Apply to This Bug?

Other (Please Describe)

### Other Type

Model

### What Type of Bug Is This?

Annoyance

### Forge Version

39.0.88

### The Aether 1 Version

1.18.1-v1.0.0

### Steps to Reproduce

N/A

### What You Expect To Happen

N/A

### What Actually Happened

N/A

### Additional Details

(just assign this one to me, I'll get round to doing it at some point in the near future... hopefully)
![2022-03-05_02 04 53](https://user-images.githubusercontent.com/52297970/156863613-39069f4a-e03d-45cd-a956-190ebf00828a.png)
![2022-03-05_02 04 59](https://user-images.githubusercontent.com/52297970/156863615-bdaf623f-7e81-4723-917f-0b0b5289bf61.png)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.

**Comment by bconlon1** [comment] 2022-03-05 02:10
Duplicate of #237

**Closed as completed by bconlon1** 2022-03-05 02:10 UTC
