### ISSUE TITLE
Bug: Game crashed when i create new world or enter old world

### ISSUE THREAD

**Issue by PhilTheGreatLOL** [Gilded-Games/The-Aether#2298] opened 2024-10-06 07:37 UTC
### What Feature Types Apply to This Bug?

System

### Other Type

None

### What Type of Bug Is This?

Crash

### Forge Version

47.3.10

### The Aether Version

1.5.0

### Is This Bug a Conflict With Another Mod?

No

### Client Log

Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered

### Crash Report (if applicable)

at
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method placeGoldenOaks(Lnet/minecraft/world/level/block/Block;Lcom/llamalad7/mixinextras/injector/wrapoperation/Operation;)Lnet/minecraft/world/level/block/state/BlockState; in aether_redux.mixins.json:common.world.GoldDungeonStructureMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap aether_redux.refmap.json
TRANSFORMER/aether@0.0NONE/com.aetherteam.aether.world.structure.AetherStructureTypes.lambda$static$6(AetherStructureTypes.java:15)

### Steps to Reproduce

Sometime
Step 1 Create new world or play old world
Step 2 Game crashed due to unexpected critical error

### What You Expect To Happen

None

### What Actually Happened

None

### Additional Details

[crash-2024-10-06_14.14.51-client.txt](https://github.com/user-attachments/files/17268514/crash-2024-10-06_14.14.51-client.txt)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by Gabi-Alex** [comment] 2024-10-06 13:08
I have the same issue. Everything is okay after downgrading to 1.4.2.

**Comment by Builderdog841** [comment] 2024-10-06 13:10
This crash is caused by Aether Redux

**Comment by PhilTheGreatLOL** [comment] 2024-10-06 13:11
I recognize that issue.

**Comment by BredyAK** [comment] 2024-10-06 16:18
have the same issue, i'm downgrading too.

**Comment by bconlon1** [comment] 2024-10-06 16:29
Duplicate of #2297

**Closed as not planned by bconlon1** 2024-10-06 16:29 UTC
