### ISSUE TITLE
Bug: incompatibility with controlled [1.19.2]

### ISSUE THREAD

**Issue by kuba26038** [Gilded-Games/The-Aether#1717] opened 2023-09-17 16:47 UTC
### What Feature Types Apply to This Bug?

System, Other (Please Describe)

### Other Type

mod incompatibility: when aether is loaded alongside the controlling mod created by mr crayfish, the controlling mod doesn't perform it's base function

### What Type of Bug Is This?

Compatibility

### Forge Version

43.2.18

### The Aether Version

aether-1.19.2-1.0.0-beta.1-forge

### Is This Bug a Conflict With Another Mod?

https://www.curseforge.com/minecraft/mc-mods/controlling

### Client Log

no latest.log is generated, as the issue can be found even in the main menu.

### Steps to Reproduce

1- open the game with controlling, aether, and framework (controlling's library)
2- open the controls menu
3- see that the controlling's changes aren't applied

### What You Expect To Happen

controlling's changes, the search bar for an example, should appear when it's installed

### What Actually Happened

controlling's changes didn't apply

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment] 2023-09-17 16:50
Duplicate of #1705

**Closed as completed by bconlon1** 2023-09-17 16:50 UTC
