### ISSUE TITLE
Feature Request: <1.20 Update>

### ISSUE THREAD

**Issue by SafeOfArsenal** [Gilded-Games/The-Aether#1642] opened 2023-08-17 04:16 UTC
### Is This an Enhancement to a Preexisting Feature?

- [ ] I confirm this request is an enhancement to a feature already in The Aether.

### What Is Your Feature Request?

A Port to 1.20 Trails and Tales

### Why Should It Be in the Mod?

Cause it would be cool

### Please Read and Confirm the Following

- [X] I have confirmed this feature is either in the original Aether mod, or improves parity between The Aether and Minecraft or other mods.
- [X] I have confirmed this suggestion is unique and has not been suggested already.

**Comment by bconlon1** [comment] 2023-08-17 04:20
Duplicate of #1490. Please look at pinned issues.

**Closed as completed by bconlon1** 2023-08-17 04:20 UTC
Labels: type/request
