### ISSUE TITLE
Bug: Game crashes on world creation

### ISSUE THREAD

**Issue by DexxKnight1** [Gilded-Games/The-Aether#2316] opened 2024-10-09 09:35 UTC
### What Feature Types Apply to This Bug?

World-Gen

### What Type of Bug Is This?

Crash

### Forge Version

47.3.11

### The Aether Version

1.5.0

### Is This Bug a Conflict With Another Mod?

FPS Reducer

### Client Log

https://gist.github.com/DexxKnight1/7cd18b4c22868f0181f3fafa2a49fa0c

### Crash Report (if applicable)

https://gist.github.com/DexxKnight1/fbbe87591679d3159d1ded52e9cf24e2

### Steps to Reproduce

1. Start the game...
2. Try to create world...
3. Game crash...

### What You Expect To Happen

To be able to create a new world.

### What Actually Happened

Even by disabling the FPS Reducer, the game keep crashing.

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contain vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this bug is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this bug to their issue tracker already.
- [X] I have confirmed that I'm reporting a bug in The Aether I, not The Aether II.

**Comment by Theguy1118590** [comment] 2024-10-09 13:09
This Happens to me aswell

**Comment by Petero48** [comment] 2024-10-09 16:46
Same here, the version "The Aether - 1.20.1-1.5.0-neoforge" crashes upon creating new world or loading a saved world. Previous versions works fine.

**Comment by bconlon1** [comment] 2024-10-09 17:45
Duplicate of #2308

**Closed as not planned by bconlon1** 2024-10-09 17:45 UTC
