### ISSUE TITLE
Bug: Add-Ons can't register custom Altar Fuels

### ISSUE THREAD

**Issue by Builderdog841** [Gilded-Games/The-Aether#2060] opened 2024-03-13 14:12 UTC
### What Feature Types Apply to This Bug?

System

### What Type of Bug Is This?

Compatibility

### Forge Version

47.1.70

### The Aether Version

1.20.1-1.2.0

### Steps to Reproduce

1. Register a new Fuel for the Altar
2. Put it into the event.enqueueWork in the FMLCommonSetupEvent
3. See how it didn't register

### What You Expect To Happen

For the fuel to register

### What Actually Happened

It didn't

### Additional Details

I have searched through the repository but didn't find anything so
here is my code, in case I did something wrong on my side:
```
    public static void registerFuels() {
        AltarBlockEntity.addItemEnchantingTime(AncientAetherBlocks.ATMOSINE_CRYSTAL.get(), 500);
    }
```

```
    private void commonSetup(final FMLCommonSetupEvent event) {
        event.enqueueWork(() -> {
            AncientAetherBlocks.registerFuels();
            AncientAetherBlocks.registerPots();
            AncientAetherBlocks.registerFlammability();

            registerComposting();
            registerDispenserBehaviors();

            AncientAetherAdvancementTriggers.init();

            Regions.register(new AncientAetherRegion(new ResourceLocation(MODID, "ancient_aether"), AncientAetherConfig.COMMON.ancient_aether_region_weight.get()));
            SurfaceRuleManager.addSurfaceRules(AetherRuleCategory.THE_AETHER, MODID, AncientAetherSurfaceData.makeRules());
        });
    }
```

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment] 2024-04-02 03:57
Could you run debugging on this to see what code is going through and what the contents of the map are with Ancient Aether to determine where the issue is arising?

**Comment by bconlon1** [comment] 2024-04-02 16:08
The fix has been determined to be using a reload listener.

**Closed as completed by bconlon1** 2024-04-02 16:08 UTC
Labels: invalid/incomplete, version/1.19.4, version/1.20.1, version/1.19.2, version/1.20.2
