### ISSUE TITLE
Bug: <title>

### ISSUE THREAD

**Issue by Devilswarchild** [Gilded-Games/The-Aether#1479] opened 2023-06-03 19:12 UTC
### What Feature Types Apply to This Bug?

Other (Please Describe)

### Other Type

Networking issue

### What Type of Bug Is This?

Unexpected Behavior

### Forge Version

45.0.57

### The Aether Version

1.0.0- beta 1, beta2, beta 3 and beta 4

### Client Log

https://gist.github.com/Devilswarchild/eef0ed80234c94fe5ada01808f766b10

### Steps to Reproduce

just when trying to join a server or even hosting a multiplayer sessions though lan

### What You Expect To Happen

ability to connect to a server like normal

### What Actually Happened

Connection Lost
Internal Exception: io.netty.handler.codec.DecoderException:
javalang.IndexOutOfBoundsException: readerIndex(12) + length(1) exceeds
writerIndex(12): PooledUnsafeDirectByteBuf(ridx: 12, widx: 12, cap: 12)

### Additional Details

![Screenshot_1](https://github.com/The-Aether-Team/The-Aether/assets/27385258/c8742ffd-0a29-4f38-86fa-95cc9e8b4959)

modlist:

[Croptopia (by thethonk)](https://www.curseforge.com/minecraft/mc-mods/croptopia)
[MidnightLib (by TeamMidnightDust)](https://www.curseforge.com/minecraft/mc-mods/midnightlib)
[AttributeFix (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/attributefix)
[Endless Biomes (by MadoctheHadoc)](https://www.curseforge.com/minecraft/mc-mods/endless-biomes)
[BlockUI (by Raycoms)](https://www.curseforge.com/minecraft/mc-mods/blockui)
[Mo' Glowstone Lamps (by TheMasterGeneral)](https://www.curseforge.com/minecraft/mc-mods/mo-glowstone-lamps)
[YUNG's Better Mineshafts (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-mineshafts-forge)
[Collective (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/collective)
[Many More Advancements (by Krzychowskyyyy)](https://www.curseforge.com/minecraft/mc-mods/many-more-advancements)
[The Twilight Forest (by Benimatic)](https://www.curseforge.com/minecraft/mc-mods/the-twilight-forest)
[Fantasy's Furniture (by ApexMdr)](https://www.curseforge.com/minecraft/mc-mods/fantasys-furniture)
[MVS - Moog's Voyager Structures (by finndog_123)](https://www.curseforge.com/minecraft/mc-mods/moogs-voyager-structures)
[Storage Racks (by Raycoms)](https://www.curseforge.com/minecraft/mc-mods/storage-racks)
[Almost Unified (by AlmostReliable)](https://www.curseforge.com/minecraft/mc-mods/almost-unified)
[CTD Core (by TheMasterGeneral)](https://www.curseforge.com/minecraft/mc-mods/ctd-core)
[Immersive Weapons (by AnonymousHacker1279)](https://www.curseforge.com/minecraft/mc-mods/immersive-weapons)
[Infused Foods (by ApexMdr)](https://www.curseforge.com/minecraft/mc-mods/infused-foods)
[AppleSkin (by squeek502)](https://www.curseforge.com/minecraft/mc-mods/appleskin)
[Reap Mod (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/reap-mod)
[Farsight [Forge] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/farsight)
[Domum Ornamentum (by OrionOnline)](https://www.curseforge.com/minecraft/mc-mods/domum-ornamentum)
[GravelMiner (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/gravelminer)
[Bad Wither No Cookie - Reloaded (by Kreezxil)](https://www.curseforge.com/minecraft/mc-mods/bad-wither-no-cookie-reloaded)
[The Aether (by TheAetherTeam)](https://www.curseforge.com/minecraft/mc-mods/aether)
[Waystones (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/waystones)
[YUNG's Better Nether Fortresses (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-nether-fortresses)
[Corail Pillar (by Corail_31)](https://www.curseforge.com/minecraft/mc-mods/corail-pillar)
[Security Craft (by Geforce132)](https://www.curseforge.com/minecraft/mc-mods/security-craft)
[Immersive structures (by ChoiceTheorem)](https://www.curseforge.com/minecraft/mc-mods/immersive-structures)
[Vanilla Plus Tools (by Raycoms)](https://www.curseforge.com/minecraft/mc-mods/vanilla-tools)
[Immersive Structures II: Nether edition (by ChoiceTheorem)](https://www.curseforge.com/minecraft/mc-mods/immersive-structures-ii-nether-edition)
[Citadel (by sbom_xela)](https://www.curseforge.com/minecraft/mc-mods/citadel)
[Oreberries Replanted (by Mrbysco)](https://www.curseforge.com/minecraft/mc-mods/oreberries-replanted)
[Just Enough Items (JEI) (by mezz)](https://www.curseforge.com/minecraft/mc-mods/jei)
[TieFix (by j_t_a_i)](https://www.curseforge.com/minecraft/mc-mods/tiefix)
[Unseen World (by sashakyotoz)](https://www.curseforge.com/minecraft/mc-mods/unseen_world)
[Skin Layers 3D (Fabric/Forge) (by tr7zw)](https://www.curseforge.com/minecraft/mc-mods/skin-layers-3d)
[Better Fps - Render Distance[Forge] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/better-fps-render-distance)
[Structure Essentials[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/structure-essentials-forge-fabric)
[Borderless Window (by nekeras)](https://www.curseforge.com/minecraft/mc-mods/borderless)
[SuperMartijn642's Config Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-config-lib)
[Rubidium (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/rubidium)
[Additional Lanterns (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/additional-lanterns)
[Better Villages - Forge (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/better-village-forge)
[playerAnimator (by KosmX)](https://www.curseforge.com/minecraft/mc-mods/playeranimator)

[Aquaculture 2 (by Shadow)](https://www.curseforge.com/minecraft/mc-mods/aquaculture)
[Creeper Firework (by DragonsPlus)](https://www.curseforge.com/minecraft/mc-mods/creeper-firework)
[Savage Ender Dragon[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/savage-ender-dragon)
[Immersive Aircraft [Fabric/Forge] (by Conczin)](https://www.curseforge.com/minecraft/mc-mods/immersive-aircraft)
[Biomes O' Plenty (by Forstride)](https://www.curseforge.com/minecraft/mc-mods/biomes-o-plenty)

[Catalogue (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/catalogue)
[Jade 🔍 (by Snownee_)](https://www.curseforge.com/minecraft/mc-mods/jade)
[Cristel Lib (by Cristelknight)](https://www.curseforge.com/minecraft/mc-mods/cristel-lib)
[AmbientSounds 5 (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/ambientsounds)
[Clumps (by Jaredlll08)](https://www.curseforge.com/minecraft/mc-mods/clumps)
[Macaw's Paths and Pavings (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-paths-and-pavings)
[FPS Monitor (by EwyBoy)](https://www.curseforge.com/minecraft/mc-mods/fps-monitor)
[Get It Together, Drops! (by bl4ckscor3)](https://www.curseforge.com/minecraft/mc-mods/get-it-together-drops)
[Ultris: Boss Expansion (by limesplatus)](https://www.curseforge.com/minecraft/mc-mods/ultris-boss-expansion)
[Ad Astra (by AlexNijjar)](https://www.curseforge.com/minecraft/mc-mods/ad-astra)
[FerriteCore (Forge) (by malte0811)](https://www.curseforge.com/minecraft/mc-mods/ferritecore)
[FLIB (by Lothrazar)](https://www.curseforge.com/minecraft/mc-mods/flib)
[Comforts (Fabric/Forge/Quilt) (by TheIllusiveC4)](https://www.curseforge.com/minecraft/mc-mods/comforts)
[Balm (Forge Edition) (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/balm)
[Sound Physics Remastered (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/sound-physics-remastered)
[MineColonies (by Raycoms)](https://www.curseforge.com/minecraft/mc-mods/minecolonies)
[TerraBlender (Forge) (by TheAdubbz)](https://www.curseforge.com/minecraft/mc-mods/terrablender)
[Advancement Plaques [Forge] (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/advancement-plaques)
[Ender Mail (by Chaosyr)](https://www.curseforge.com/minecraft/mc-mods/ender-mail)
[Cosmetic Armor Reworked (by LainMI)](https://www.curseforge.com/minecraft/mc-mods/cosmetic-armor-reworked)
[YUNG's Extras (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-extras)
[JourneyMap (by techbrew)](https://www.curseforge.com/minecraft/mc-mods/journeymap)
[Packed Up (Backpacks) (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/packed-up-backpacks)
[ESSENTIAL Mod (by SparkUniverse_)](https://www.curseforge.com/minecraft/mc-mods/essential-mod)
[Corail Woodcutter (by Corail_31)](https://www.curseforge.com/minecraft/mc-mods/corail-woodcutter)
[The Undergarden (by Quek04)](https://www.curseforge.com/minecraft/mc-mods/the-undergarden)
[Not Enough Crashes (Forge) (by NatanFudge)](https://www.curseforge.com/minecraft/mc-mods/not-enough-crashes-forge)
[Library Ferret - Forge (by jtl_elisa)](https://www.curseforge.com/minecraft/mc-mods/library-ferret-forge)
[Multi-Piston (by Raycoms)](https://www.curseforge.com/minecraft/mc-mods/multi-piston)
[Bookshelf (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/bookshelf)
[Iceberg [Forge] (by Grend_G)](https://www.curseforge.com/minecraft/mc-mods/iceberg)
[ForgeEndertech (by EnderLanky)](https://www.curseforge.com/minecraft/mc-mods/forgeendertech)
[Better Combat [Fabric & Forge] (by daedelus_dev)](https://www.curseforge.com/minecraft/mc-mods/better-combat-by-daedelus)
[Structurize (by Raycoms)](https://www.curseforge.com/minecraft/mc-mods/structurize)
[Stylecolonies (by Raycoms)](https://www.curseforge.com/minecraft/mc-mods/stylecolonies)
[Large Ore Deposits (by EnderLanky)](https://www.curseforge.com/minecraft/mc-mods/large-ore-deposits)
[Oculus (by Asek3)](https://www.curseforge.com/minecraft/mc-mods/oculus)
[Forbidden and Arcanus (by cesar_zorak)](https://www.curseforge.com/minecraft/mc-mods/forbidden-arcanus)
[Physics Mod (by haubna)](https://www.curseforge.com/minecraft/mc-mods/physics-mod)
[Game Menu Mod Option [Forge] (by morimori0317)](https://www.curseforge.com/minecraft/mc-mods/gamemenumodoption)
[Neat (by Vazkii)](https://www.curseforge.com/minecraft/mc-mods/neat)
[Cooking for Blockheads (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/cooking-for-blockheads)
[TrashSlot (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/trashslot)
[L_Ender 's Cataclysm (by mcl_ender)](https://www.curseforge.com/minecraft/mc-mods/l_ender-s-cataclysm)
[Transparent (by Trikzon)](https://www.curseforge.com/minecraft/mc-mods/transparent)
[YUNG's API (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-api)
[Eccentric Tome (by EccentricVamp)](https://www.curseforge.com/minecraft/mc-mods/eccentric-tome)
[Configured (by MrCrayfish)](https://www.curseforge.com/minecraft/mc-mods/configured)
[Inventory Essentials (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/inventory-essentials)
[When Dungeons Arise - Forge! (by Aureljz)](https://www.curseforge.com/minecraft/mc-mods/when-dungeons-arise)
[Fast Portals (by gluegunner4)](https://www.curseforge.com/minecraft/mc-mods/fast-portals)
[Portable Crafting Table (by 00theblackwolf00)](https://www.curseforge.com/minecraft/mc-mods/portable-crafting-table)
[Valhelsia Core (by ValhelsiaTeam)](https://www.curseforge.com/minecraft/mc-mods/valhelsia-core)
[Server Performance - Smooth Chunk Save[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/smooth-chunk-save)
[Immersive Paintings [Fabric/Forge] (by Conczin)](https://www.curseforge.com/minecraft/mc-mods/immersive-paintings)
[Enchantment Descriptions (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions)
[Corpse (by henkelmax)](https://www.curseforge.com/minecraft/mc-mods/corpse)
[Unstructured [Fabric/Forge] (by Cristelknight)](https://www.curseforge.com/minecraft/mc-mods/unstructured)
[Double Doors (by Serilum)](https://www.curseforge.com/minecraft/mc-mods/double-doors)
[SuperMartijn642's Core Lib (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/supermartijn642s-core-lib)
[The Lost Cities (by McJty)](https://www.curseforge.com/minecraft/mc-mods/the-lost-cities)
[CreativeCore (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/creativecore)
[The One Probe (by McJty)](https://www.curseforge.com/minecraft/mc-mods/the-one-probe)
[Rapid Leaf Decay (by GeheimagentNr1)](https://www.curseforge.com/minecraft/mc-mods/rapid-leaf-decay)
[Advent of Ascension (Nevermine) (by Scimiguy)](https://www.curseforge.com/minecraft/mc-mods/advent-of-ascension-nevermine) currently disabled
[Macaw's Trapdoors (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-trapdoors)
[Immersive Armors [Fabric/Forge] (by Conczin)](https://www.curseforge.com/minecraft/mc-mods/immersive-armors) currently disabled
[Mo' Glowstone (by TheMasterGeneral)](https://www.curseforge.com/minecraft/mc-mods/mo-glowstone)
[Exotelcraft (by TKD_Kedis)](https://www.curseforge.com/minecraft/mc-mods/exotelcraft)
[Ash API (by Trikzon)](https://www.curseforge.com/minecraft/mc-mods/ash-api)
[Botarium (by CodexAdrian)](https://www.curseforge.com/minecraft/mc-mods/botarium)
[Chisels & Bits - For Forge (by AlgorithmX2)](https://www.curseforge.com/minecraft/mc-mods/chisels-bits)
[Resourceful Lib (by ThatGravyBoat)](https://www.curseforge.com/minecraft/mc-mods/resourceful-lib)
[KleeSlabs (by BlayTheNinth)](https://www.curseforge.com/minecraft/mc-mods/kleeslabs)
[Clickable advancements[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/clickable-advancements)
[Additional Banners (by DarkhaxDev)](https://www.curseforge.com/minecraft/mc-mods/additional-banners)
[Biome Music[Forge/Fabric] (by someaddon)](https://www.curseforge.com/minecraft/mc-mods/biome-music)
[Resourceful Config (by ThatGravyBoat)](https://www.curseforge.com/minecraft/mc-mods/resourceful-config)
[Why stacks of 16? (by LaidBackSloth42)](https://www.curseforge.com/minecraft/mc-mods/why-stacks-of-16)
[Architectury API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/architectury-api)
[YUNG's Better Dungeons (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-dungeons)
[Enhanced Farming (by Mrbysco)](https://www.curseforge.com/minecraft/mc-mods/enhanced-farming)
[Wormhole (Portals) (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/wormhole-portals)
[Just Another Rotten Flesh to Leather Mod (by alexdaum1)](https://www.curseforge.com/minecraft/mc-mods/just-another-rotten-flesh-to-leather-mod)
[Macaw's Doors (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-doors)
[Immersive Weapons Compatibility Bridge (by AnonymousHacker1279)](https://www.curseforge.com/minecraft/mc-mods/immersive-weapons-compatibility-bridge) currently disabled
[Cloth Config API (Fabric/Forge) (by shedaniel)](https://www.curseforge.com/minecraft/mc-mods/cloth-config)
[Saturn (by AbdElAziz333)](https://www.curseforge.com/minecraft/mc-mods/saturn)
[Structure Gel API (by ModdingLegacy)](https://www.curseforge.com/minecraft/mc-mods/structure-gel-api)
[YUNG's Better Ocean Monuments (Forge) (by YUNGNICKYOUNG)](https://www.curseforge.com/minecraft/mc-mods/yungs-better-ocean-monuments)
[Entity Culling Fabric/Forge (by tr7zw)](https://www.curseforge.com/minecraft/mc-mods/entityculling)
[Blue Skies (by ModdingLegacy)](https://www.curseforge.com/minecraft/mc-mods/blue-skies) currently disabled
[Ad Astra!: Giselle Addon (by 지젤쟝다)](https://www.curseforge.com/minecraft/mc-mods/ad-astra-giselle-addon)
[PlayerRevive (by CreativeMD)](https://www.curseforge.com/minecraft/mc-mods/playerrevive)
[Re-chiseled (by SuperMartijn642)](https://www.curseforge.com/minecraft/mc-mods/rechiseled)
[Macaw's Fences and Walls (by sketch_macaw)](https://www.curseforge.com/minecraft/mc-mods/macaws-fences-and-walls)
[Towns and Towers (by Biban_Auriu)](https://www.curseforge.com/minecraft/mc-mods/towns-and-towers)
[GeckoLib (by Gecko)](https://www.curseforge.com/minecraft/mc-mods/geckolib)

### Please Read and Confirm The Following

- [X] I have confirmed this bug can be replicated without the use of Optifine.
- [X] I have confirmed this bug is on the most recently supported version of Minecraft.
- [X] I have confirmed the details provided in this report are concise as possible and does not contained vague information (ie. Versions are properly recorded, answers to questions are clear).
- [X] I have confirmed this issue is unique and has not been reported already.
- [X] If playing on a modpack, I have reported this issue to their issue tracker already.

**Comment by bconlon1** [comment] 2023-06-03 19:15
Does everything work fine without Aether included? Also please do not list every beta version as your version, I need to know what specific version is being used by the clients and server.

**Comment by Devilswarchild** [comment] 2023-06-03 19:17
reason I listed them all is cause after each launch and connection test, I downgraded it starting with the latest which is beta 4 just to show that the issue persisted through all the updates. and yes everything works just fine with the aether disabled.

**Comment by bconlon1** [comment] 2023-06-03 19:18
Have you also tried testing removing other mods but not Aether?

**Comment by Devilswarchild** [comment] 2023-06-03 19:19
I have actually removed a couple others due to them causing weird log spam type issues and reported one of them to their respective mod author, others caused various exit codes 1 and -1 respective. those are all either downgraded to working versions or disabled altogether until a fix  can be implemented into a future update.

**Comment by Devilswarchild** [comment] 2023-06-03 19:21
i will now commence a minimal instance test

**Comment by bconlon1** [comment] 2023-06-03 19:21
I mean have you narrowed down confirming whether this issue is just caused by Aether or if it's caused by an interaction between the Aether and a specific other mod by removing mods until either the error went away or the only mod left was the Aether?

**Comment by Devilswarchild** [comment] 2023-06-03 19:24
im now running the test with just essentials mod, jade, jei, neat, the one probe and the aether enabled.

**Comment by Devilswarchild** [comment] 2023-06-03 19:25
with just those enabled, issue still occured. now proceeding to remove essential and see what happens

**Comment by Devilswarchild** [comment] 2023-06-03 19:27
error occured again, now removing neat

**Comment by Devilswarchild** [comment] 2023-06-03 19:28
and the error continues, now removing the one probe

**Comment by Devilswarchild** [comment] 2023-06-03 19:29
now removing jade as the error occured once more

**Comment by Cinex20** [comment] 2023-06-03 19:29
Why have Structure Gel enabled if you disabled Blue Skies?

**Comment by Devilswarchild** [comment] 2023-06-03 19:30
now its just the aether by itself

**Comment by bconlon1** [comment] 2023-06-03 19:31
Could you now please provide the logs from both the server during the time of join and the client during the time of join when this error occurs?

**Comment by Devilswarchild** [comment] 2023-06-03 19:32
I dont have access to this particular servers logs at all. seeing as the address for it is literally test.prisonfun.com which I can connect to just fine without the aether as from Ive gather all over the web is just basically a connection test server in which a lot of people just like to horse around on

**Comment by Burning-Cactus** [comment] 2023-06-03 19:33
I'm just gonna chime in and say that this is usually caused by a different mod version being used between the client and server. The game is confused because things aren't matching up.

**Comment by bconlon1** [comment] 2023-06-03 19:33
Which sounds like it is the case if you are trying to join a server that doesn't even have the mod installed.

**Comment by Devilswarchild** [comment] 2023-06-03 19:34
> I'm just gonna chime in and say that this is usually caused by a different mod version being used between the client and server. The game is confused because things aren't matching up.

well this particular server will allow modded clients to login but forces the mods to a disabled state

**Comment by Burning-Cactus** [comment] 2023-06-03 19:35
That's simply not how it works. Forge still has mods loaded on your client, so the game's code, registered items and entities, and etc. will all be different. The server can NOT ever change the code on your machine.

**Comment by Devilswarchild** [comment] 2023-06-03 19:37
> That's simply not how it works. Forge still has mods loaded on your client, so the game's code, registered items and entities, and etc. will all be different. The server can NOT ever change the code on your machine.

nevertheless i am still abled to connect to the server with the aether disabled.


also here are the logs for just the ather enabled 

https://gist.github.com/Devilswarchild/ea416928256609d5699a085b5479dbe4

**Comment by bconlon1** [comment] 2023-06-03 19:40
Have you actually tried to test joining a server that has the Aether, with the Aether mod?

**Comment by Devilswarchild** [comment] 2023-06-03 19:41
no I haven't actually cause I dont currently know of one, due to the fact that my modpack contains the essential mod which kinda negates the need for a dedicated server

**Comment by bconlon1** [comment] 2023-06-03 19:42
Then have you tried hosting with the Essential mod, with only Aether installed?

**Comment by Devilswarchild** [comment] 2023-06-03 19:44
yes, same issue

**Comment by bconlon1** [comment] 2023-06-03 19:44
Then could you give the logs of the Essential "server" (the host), and the client trying to join that is getting the error?

**Comment by Devilswarchild** [comment] 2023-06-03 19:45
the essential mod doesnt generate any logs to my knowledge

**Comment by Devilswarchild** [comment] 2023-06-03 19:45
but let me double check that

**Comment by Devilswarchild** [comment] 2023-06-03 19:46
nope, no logs in its folder

**Comment by bconlon1** [comment] 2023-06-03 19:46
The Essential mod should be hosting from your client, and the client always generates logs.

**Comment by Devilswarchild** [comment] 2023-06-03 19:47
yes, and I have provided you with all the logs that I can generate. but ill run it again with the aether and essential as the only enabled mods
gimme just a few minutes

**Comment by bconlon1** [comment] 2023-06-03 19:48
Yes, and the previous logs you provided me had 100 other mods installed. Please provide me the logs but without those mods and only the Aether.

**Comment by Devilswarchild** [comment] 2023-06-03 19:49
> > That's simply not how it works. Forge still has mods loaded on your client, so the game's code, registered items and entities, and etc. will all be different. The server can NOT ever change the code on your machine.
> 
> nevertheless i am still abled to connect to the server with the aether disabled.
> 
> also here are the logs for just the ather enabled
> 
> https://gist.github.com/Devilswarchild/ea416928256609d5699a085b5479dbe4

the link above is with just the aether

**Comment by bconlon1** [comment] 2023-06-03 19:50
That is only the logs from one end of the connection. I already said I need logs from both ends of the connection.

**Comment by Devilswarchild** [comment] 2023-06-03 19:52
well I can't give you the other end of the connection because I don't have anyone to help me with this. Im a modpack creator who is doing all of this solo

**Comment by bconlon1** [comment] 2023-06-03 19:52
Then where did the connection error you gave in the post come from?

**Comment by Devilswarchild** [comment] 2023-06-03 19:54
test.prisonfun.com is the server address I use to test network related issues with my modpack. that address was obtained from several troubleshooting guides across the web which has been very reliable to detect networking issues. and all the issues I've ever had with my modpack have all been the same exact error across all the mc versions of my modpack. I dont not own or have access to any of the files associated with the server.

**Comment by bconlon1** [comment] 2023-06-03 19:55
> yes, same issue

Then how did you receive the same connection error from Essential if you only tried ever joining this server?

**Comment by Devilswarchild** [comment] 2023-06-03 19:58
I was simply referring to the fact that essential does ,if I can word this correctly in a way that'll help with the understanding it of it, is replaces/improves the open to lan feature by making the "host" pc act as a dedicated server without the actual need of a dedicated server if that makes any sense

**Comment by bconlon1** [comment] 2023-06-03 19:58
I know that, that doesn't answer my question though.

**Comment by Devilswarchild** [comment] 2023-06-03 19:58
however, if the test server I connect to is throwing the io.netty.handler error then either me or if I manage to get someoone to connect to would also throw the same error due to it being a multiplayer connection

**Comment by bconlon1** [comment] 2023-06-03 19:59
That is because, as stated before, the connection server does not have Aether installed.

**Comment by Devilswarchild** [comment] 2023-06-03 20:00
and I also tried upgrading forge from .57 to .66 and the same issue occurs there which leads me to believe that, hear me out, its quite possible that a line of code could have gotten overlooked or possibly had a typo but what do I know. Im not a coder

**Comment by Devilswarchild** [comment] 2023-06-03 20:01
> That is because, as stated before, the connection server does not have Aether installed.

i can assure that isnt the case because an earlier version of my modpack also has the aether installed and the server didnt and I was able to connect just fine

**Comment by Devilswarchild** [comment] 2023-06-03 20:02
and by earlier version, I mean of course a version of my modpack on an earlier version of minecraft

**Comment by bconlon1** [comment] 2023-06-03 20:03
Not all mods are guaranteed to be able to connect with vanilla servers, because its a vanilla server. It cannot account for every change a mod makes which may make them incompatible. I don't even understand at this point why it matters whether you can connect to this vanilla server or not with your modpack.

**Comment by Devilswarchild** [comment] 2023-06-03 20:05
bc If I cant connect to this test server then none of the players using this version of my modpack are going to be able to connect with their friends. (if any of them have any)

**Comment by bconlon1** [comment] 2023-06-03 20:05
And how are you sure of this if you have not tested joining a server that has the modpack on it with a client that has the modpack?

**Comment by Devilswarchild** [comment] 2023-06-03 20:06
bc the only person I could potentially try to have help me with this is currently engaged in other activities and wont be available for quite some time

**Comment by Devilswarchild** [comment] 2023-06-03 20:07
like an undisclosed amount of time

**Comment by Devilswarchild** [comment] 2023-06-03 20:07
ergo I dont know if or when they will be available.

**Comment by bconlon1** [comment] 2023-06-03 20:08
So you are not actually sure whether there is an issue with either the Aether or your modpack.

**Comment by Devilswarchild** [comment] 2023-06-03 20:10
oh no, im very sure. if it happens one place, it happens on the other,

**Comment by Jonathing** [comment] 2023-06-03 20:10
🍿

**Comment by Devilswarchild** [comment] 2023-06-03 20:17
ok i managed to get ahold of this person to do an essentials mod test with the aether. she was able to connect just fine. so my apologies. however tis particular instance doesnt always happen. more often then not with my mopack when I get the error one place it always happens in the other place. this is probably the 1% where there is actually no issue using a (insert mod name here) with essentials.

**Comment by Jonathing** [comment] 2023-06-03 20:20
Go ahead, install Aether on your default Forge client, then try to login to a vanilla server. It won't work.

**Comment by bconlon1** [comment] 2023-06-03 20:22
Please do more research before you report issues when you have not actually proven them, just because you assume it exists, and listen to developers who actually know what they're talking about with their mods. We have an official server that has not had this issue, Modding Legacy has an Aether server that has not had this issue, and the Twilight Forest developers also have a modpack server that has Aether installed and has not had this issue. The issue only occurred when trying to join servers using an incompatible client (as you have done here). The Aether mod has also been [tested by the Essential developers themselves](https://twitter.com/EssentialMod/status/1657056035960389637) with the Essential mod. Closing this issue now.

**Closed as not planned by bconlon1** 2023-06-03 20:22 UTC
Labels: invalid/incomplete
